### ISSUE TITLE
Rooms aren't working properly on the demo

### ISSUE THREAD

**Issue by Oxyrus** [bnhansn/sling#2]
I've registered on the demo website (http://sling-chat.s3-website-us-west-2.amazonaws.com/), creating and joining a room works perfectly, however I'm unable to send any messages.

**Comment by bnhansn** [comment]
Which browser are you using, or are there any errors printing in the console? There is currently an issue with websocket connections in Safari https://github.com/bnhansn/sling/issues/1.

**Comment by Oxyrus** [comment]
I'm using Firefox, the error printed to console is `Firefox can't stablish a connection to the server at ws://nameless-reaches-32969.herokuapp.com/socket/websocket?token=very_long_token`

**Comment by bnhansn** [comment]
Fixed by adding the frontend domain to check_origin in the endpoint configuration https://github.com/bnhansn/sling/commit/8366cb8ddcbcdd9b6cd3def5db9a9d053ce66c65
