### ISSUE TITLE
In tutorial Part 1 - initial run of /api server gets route error

### ISSUE THREAD

**Issue by cortfritz** [bnhansn/sling#5]
I am getting the following: "no route found for GET / (Sling.Router)" in web/router.ex

Occurring when I test at the instruction "If you open up http://localhost:4000 you should see the Phoenix welcome page." 

This is just after configuring the server, creating the db, just before the second instruction to git commit.

I've carefully gone through the instructions a few times to make sure I wasn't making a mistake.  Possible I'm still doing something wrong.

**Comment by Chinooo** [comment]
If you enable the --no-html --no-brunch you will not have a pagecontroller , so try to only do:

mix phoenix.new sling  --no-brunch 

but this is old the new version of phoenix try with this:

mix phx.new sling --no-brunch

**Comment by mutp** [comment]
Remove --no-html.
`mix phx.new sling --no-brunch` worked for me.

**Comment by cortfritz** [comment]
thanks.  updated to Phoenix 1.3.0, elixir 1.4.5, erlang 19, removed --no-html and it works fine.  thank you for the assist.
